# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["blog"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/N-logo.png"

[footer]
customText = "Noha Writes"

[dateFormat]
published = "02 Jan 2006"
lastUpdated = "02 Jan 2006 15:04 MST"

[sidebar]
emoji = "ðŸ’«"
subtitle = "Cybersecurity Enthusiast and Writer"

[sidebar.avatar]
enabled = true
local = true
src = "img/profile.jpg"

[article]
headingAnchor = false
math = false
readingTime = true
showDate = false

[article.license]
enabled = false
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = false

